### ISSUE TITLE
Fix Documentation Github Action

### ISSUE THREAD

**Issue by quothbonney** [FAA-VAIL-Project/openGCAS#28]
The documentation GitHub action is blocking me from pushing the Raster Query System PR I've been working on for almost a month now. I have not messed with the documentation at all, so I have no idea what is causing this to happen. Please fix it or temporarily disable it to allow the push.

**Comment by quothbonney** [comment]
Bumping up. Documentation action is still broken. The logs show it is returning a 403 server error from the .git. My PR is now passing to a modified Build action for new deps.

**Comment by walter-weinmann** [comment]
Due to unsolvable problems with access rights, I removed the automated update of the documentation.
